# fly.toml app configuration file generated for dashyucarroback
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dashyucarroback"
primary_region = "dfw" # Puedes validar esto según tu cuenta de Fly, habitualmente qro, ewr, etc.


[env]
  PORT = "8080"
  DB_FILE = "/data/dashboard.db" # Apuntamos la DB al volumen persistente

[mounts]
  source = "yucarro_data"        # Nombre del disco duro que configuraste en Fly
  destination = "/data"          # Ruta dentro de la máquina donde se monta

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[http_service.concurrency]
  type = "requests"
  hard_limit = 250
  soft_limit = 200

  [[http_service.checks]]
    grace_period = "1s"
    interval = "15s"
    method = "get"
    path = "/api/health"
    timeout = "2s"
